const PDFDocument = require('pdfkit');
const { v4: uuidv4 } = require('uuid');
const { cloudinary } = require('../config/cloudinary');
const db = require('../config/database');
const logger = require('../config/logger');
const { PassThrough } = require('stream');

const createReport = async (scanId) => {
  const { rows: [scan] } = await db.query(
    `SELECT s.*, u.full_name, u.email, b.name as building_name, b.address, b.building_type
     FROM scans s
     JOIN users u ON s.user_id = u.id
     LEFT JOIN buildings b ON s.building_id = b.id
     WHERE s.id = $1`,
    [scanId]
  );
  if (!scan) throw new Error(`Scan ${scanId} not found`);

  const pdfBuffer = await generatePDF(scan);
  const pdfUrl    = await uploadPDFToCloudinary(pdfBuffer, scanId);
  const shareToken = uuidv4().replace(/-/g, '');

  const { rows: [report] } = await db.query(
    `INSERT INTO reports (scan_id, user_id, title, summary, content, pdf_url, share_token)
     VALUES ($1, $2, $3, $4, $5, $6, $7)
     ON CONFLICT (scan_id) DO UPDATE SET pdf_url = $6, updated_at = NOW()
     RETURNING *`,
    [
      scanId,
      scan.user_id,
      `Crack Detection Report — ${scan.building_name || 'Unknown Building'}`,
      buildSummary(scan),
      JSON.stringify(scan.ai_results),
      pdfUrl,
      shareToken,
    ]
  );

  return report;
};

const buildSummary = (scan) => {
  const r = scan.ai_results || {};
  return `Health Score: ${scan.health_score}% | Risk: ${scan.risk_level} | Damages: ${scan.total_damages}`;
};

const generatePDF = (scan) =>
  new Promise((resolve, reject) => {
    const doc    = new PDFDocument({ size: 'A4', margin: 50 });
    const chunks = [];
    doc.on('data', c => chunks.push(c));
    doc.on('end',  () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const ai = scan.ai_results || {};

    // ── Header
    doc.fontSize(22).fillColor('#1e40af').text('CrackDetectX', { align: 'center' });
    doc.fontSize(14).fillColor('#374151').text('Structural Crack Detection Report', { align: 'center' });
    doc.moveDown();
    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#e5e7eb').stroke();
    doc.moveDown();

    // ── Building Info
    doc.fontSize(13).fillColor('#1f2937').text('Building Information', { underline: true });
    doc.moveDown(0.5);
    const info = [
      ['Building Name',  scan.building_name || 'N/A'],
      ['Address',        scan.address || 'N/A'],
      ['Building Type',  scan.building_type || 'N/A'],
      ['Inspector',      scan.full_name],
      ['Scan Date',      new Date(scan.created_at).toLocaleDateString()],
    ];
    info.forEach(([label, value]) => {
      doc.fontSize(10).fillColor('#6b7280').text(`${label}:`, { continued: true });
      doc.fillColor('#111827').text(` ${value}`);
    });
    doc.moveDown();

    // ── Results Summary
    doc.fontSize(13).fillColor('#1f2937').text('Analysis Results', { underline: true });
    doc.moveDown(0.5);

    const riskColor = { low: '#16a34a', medium: '#d97706', high: '#dc2626', critical: '#7f1d1d' };
    doc.fontSize(11).fillColor('#374151').text(`Health Score: `)
       .fillColor(scan.health_score > 70 ? '#16a34a' : '#dc2626')
       .text(`${scan.health_score}%`, { continued: false });

    doc.fontSize(11).fillColor('#374151').text('Risk Level: ', { continued: true });
    doc.fillColor(riskColor[scan.risk_level] || '#374151')
       .text((scan.risk_level || 'N/A').toUpperCase());

    doc.fontSize(11).fillColor('#374151').text(`Total Damages Detected: ${scan.total_damages}`);
    doc.moveDown();

    // ── Detections
    if (ai.detections && ai.detections.length > 0) {
      doc.fontSize(13).fillColor('#1f2937').text('Detected Issues', { underline: true });
      doc.moveDown(0.5);
      ai.detections.forEach((d, i) => {
        doc.fontSize(10).fillColor('#374151')
           .text(`${i + 1}. ${d.class_name.replace(/_/g,' ')} — Confidence: ${(d.confidence * 100).toFixed(1)}% — Severity: ${d.severity}`);
      });
      doc.moveDown();
    }

    // ── Recommendations
    if (ai.recommendations && ai.recommendations.length > 0) {
      doc.fontSize(13).fillColor('#1f2937').text('Recommendations', { underline: true });
      doc.moveDown(0.5);
      ai.recommendations.forEach((rec, i) => {
        doc.fontSize(10).fillColor('#374151').text(`• ${rec}`);
      });
      doc.moveDown();
    }

    // ── Footer
    doc.moveDown(2);
    doc.fontSize(9).fillColor('#9ca3af')
       .text(`Generated by CrackDetectX on ${new Date().toISOString()} — Confidential`, { align: 'center' });

    doc.end();
  });

const uploadPDFToCloudinary = (buffer, scanId) =>
  new Promise((resolve, reject) => {
    const stream = cloudinary.uploader.upload_stream(
      { folder: 'crackdetectx/reports', resource_type: 'raw', public_id: `report_${scanId}`, format: 'pdf' },
      (err, result) => err ? reject(err) : resolve(result.secure_url)
    );
    const pass = new PassThrough();
    pass.end(buffer);
    pass.pipe(stream);
  });

const generateShareToken = async (reportId, hoursValid = 72) => {
  const token     = uuidv4().replace(/-/g, '');
  const expiresAt = new Date(Date.now() + hoursValid * 3600 * 1000);
  await db.query(
    'UPDATE reports SET share_token = $1, share_expires_at = $2, is_shared = TRUE WHERE id = $3',
    [token, expiresAt, reportId]
  );
  return { token, expiresAt };
};

module.exports = { createReport, generateShareToken };